#!/bin/bash

OC_HOME="$(dirname "$(realpath "$0")")"
USR_CMD=$1

#user feedback messages
UNRECOGNISED_COMMAND_OPTION="usage: octocom does not recognise the option you provided for this command.."
UNRECOGNISED_OC_COMMAND="usage: octocom needs you to give it a command to run.."
UNKNOWN_OC_COMMAND="usage: octocom does not understand the command you gave it to run.."
NO_GIT_FOUND="setup: octocom could not find GIT anywhere on this host, please check this and try again?"
CONFIG_QUESTION_EMAIL_ADDRESS="config: oops! octocom needs the email address you want to use in your commits?"
CONFIG_UNKNOWN_EMAIL_ADDRESS="config: don't be like that, you need to give octocom an email address to use in your commits.."
CONFIG_QUESTION_REAL_NAME="config: oops! octocom needs the name you want to use in your commits? Like 'John Snow'."
CONFIG_UNKNOWN_REAL_NAME="config: don't be like that, you need to give octocom a name to use in your commits.."
USAGE_NO_OPTIONS_REQUIRED="usage: this command does not use options at the moment"
USAGE_EXPECTS_OPTIONS="usage: the command expects at least one option to be provided."

for file in $OC_HOME/functions/*; do source "$file"; done

checkDefaultConfigSettings

#list of available commands and allowed option characters
declare -A GMT_CMD
GMT_CMD=(
	["cl"]=""	#clear
	["pl"]="'git pull <repo> <current branch>'. <repo> will default to 'origin' and pull will be for the currently checked out branch."
	["ps"]="'git push <repo> <current branch>'. <repo> will default to 'origin' and push will be for the currently checked out branch."
	["cm"]="'git commit -a' Do an annotated commit of all staged canges to the local branch."
	["co"]=""	#checkout
	["df"]=""	#diff
	["lg"]=""	#log
	["mg"]=""	#merge master
	["nb"]=""   #checkout -b
	["cn"]=""	#clone
	["ft"]=""	#fetch
	["ra"]=""	#remote add
	["br"]=""	#branch
	["mt"]=""	#mergetool
	["nb"]=""	#new local branch
	["mv"]=""	#move files
	["st"]=""	#view status
	["help"]=""
)

#handle command run and options given
if [ -z $1 ]; then
	#add description indicating -h for more info on available commands
	echo $UNRECOGNISED_OC_COMMAND
	exit 1
elif [[ -z ${GMT_CMD[$1]+1} ]]; then
	echo $UNKNOWN_OC_COMMAND
	exit 1
fi

#example usage: oc cl feature
#todo: assign inputs to more descriptive variables(?)
$1 $2 $3
